version: "3.8"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  clickhouse-server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  clickhouse-client:
    image: yandex/clickhouse-client
    command: [ '--host', 'server' ]

  database:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    command: [ "redis-server", "--save", "''" ]
    restart: always
    ports:
      - "6377:6379"
