port: "8090"

db:
  username: "postgres"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6377"
  dbcount: "0"

clickHouse:
  host: "localhost"
  port: "8123"
