// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseRequest) Reset()         { *m = ResponseRequest{} }
func (m *ResponseRequest) String() string { return proto.CompactTextString(m) }
func (*ResponseRequest) ProtoMessage()    {}
func (*ResponseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *ResponseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseRequest.Unmarshal(m, b)
}
func (m *ResponseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseRequest.Marshal(b, m, deterministic)
}
func (m *ResponseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseRequest.Merge(m, src)
}
func (m *ResponseRequest) XXX_Size() int {
	return xxx_messageInfo_ResponseRequest.Size(m)
}
func (m *ResponseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseRequest proto.InternalMessageInfo

func (m *ResponseRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type UserResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*ResponseRequest)(nil), "main.ResponseRequest")
	proto.RegisterType((*UserRequest)(nil), "main.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "main.UserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x93, 0x92, 0x49, 0xcf,
	0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c,
	0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xa8, 0x51, 0x52, 0xe4, 0xe2, 0x0f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf,
	0x2b, 0x4e, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x51, 0x52, 0xe4, 0xe2, 0x0e, 0x2d, 0x4e,
	0x2d, 0x82, 0x49, 0x0b, 0x71, 0xb1, 0x94, 0x96, 0x42, 0x15, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0x5e,
	0x5c, 0x3c, 0x10, 0x25, 0x10, 0x93, 0x40, 0x6a, 0xf2, 0x12, 0x73, 0x53, 0x61, 0x6a, 0x40, 0x6c,
	0x21, 0x01, 0x2e, 0xe6, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0xb0, 0xb9, 0x20, 0xa6, 0x90, 0x08, 0x17,
	0x6b, 0x6a, 0x6e, 0x62, 0x66, 0x8e, 0x04, 0x33, 0x58, 0x19, 0x84, 0x63, 0xd4, 0xce, 0xc8, 0xc5,
	0x1e, 0x92, 0x5a, 0x5c, 0xe2, 0x58, 0x90, 0x29, 0xe4, 0xc1, 0xc5, 0xe2, 0x9a, 0x9c, 0x91, 0x2f,
	0x24, 0xaa, 0x07, 0xf2, 0x8a, 0x1e, 0x9a, 0x4b, 0xa5, 0xb0, 0x0b, 0x2b, 0x09, 0x35, 0x5d, 0x7e,
	0x32, 0x99, 0x89, 0x47, 0x88, 0x4b, 0x3f, 0x35, 0x39, 0x23, 0x5f, 0xbf, 0x3a, 0x33, 0xa5, 0x56,
	0xc8, 0x88, 0x8b, 0xdd, 0x3d, 0xb5, 0x04, 0xe4, 0x48, 0x21, 0x41, 0x88, 0x2e, 0x24, 0x3f, 0x49,
	0x09, 0x21, 0x0b, 0x41, 0x0c, 0x53, 0x62, 0x70, 0xe2, 0x8c, 0x62, 0xd7, 0xd3, 0x07, 0x07, 0x53,
	0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x85, 0x3f, 0xf9, 0x5f, 0x01,
	0x00, 0x00,
}
